README.md

added my fun fact

---

README.md

added fun fact

---

README.md

Salutations! Please review and approve these fun changes to the README.md file.
Thx

add my fun(ish) fact

---

README.md

Add fun fact

---

README.md

Whoopsies! I accidentally used @heratyian branch!!

Added a fun fact about Alex M.

---

README.md

brenda fun fact

---

README.md

Gaze upon my funne fakte, ye coederrs, and despair!!

Calvy's  funne fakte

---

README.md

I added the fact for Samuel Lubliner: I ride my bike to work

Add Samuel Lubliner fact about bike

---

README.md

added fun fact about David Le.

added fun fact about David.

---

README.md

added gjg fun fact

---

README.md

Added my name fun fact

---

README.md

kiowa's fun fact

---

README.md

Lamontfunfact

---

README.md

This is my fun fact about myself in the READ ME file

adding fun facts to the new cohort table

---

README.md

shared a fun fact

---

README.md

added benny's fun fact

---

README.md

Someone help me please I need this

jeremy pull request help

---

README.md

adds my fun fact

---

README.md

alonzo's fun-fact

---

README.md

i think i did it correctly this time. i have no idea why it deleted and added the alonzo's fact tho. it looks the same and i never touched his fact >.<

Brian interestingfactinreadme

---

README.md

Mp-add-fun-fact

---

README.md

added fun fact for merrill huang

added fun fact for merrill huang

---

README.md

Add Vivian's fun fact

---

README.md

Revert "Add Vivian's fun fact"

---

README.md

Revert "Brian_L fun fact"

---

README.md

I just deleted copy of my line. Idk how it appeared in the code.

deleted the extra line

---

README.md

adding branch and edit to README

added fact

---

README.md

Added teresa-pham branch and committed fun fact under 2024-9.1 to this branch

created teresa-pham branch and added fun fact

---

README.md

Added my fun fact and removed trailing spaces.

joel h fun fact

---

README.md

Melissa Martinez added fun fact.

---

README.md

Berhane's fun fact

---

README.md

added Darius's fun fact
